[package]
name = "ampere"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
slotmap = "1.0.6"
ahash = "0.8.2"
lasso = "0.6.0"
colored = "2.0.0"
ariadne = "0.1.5"